# Generated by Django 5.2.8 on 2025-11-18 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0012_add_value_uniqueness_checks'),
        migrations.swappable_dependency(getattr(settings, 'EAV_ATTRIBUTE_MODEL', 'eav.Attribute')),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=getattr(settings, 'EAV_ATTRIBUTE_MODEL', 'eav.Attribute'), verbose_name='Attribute'),
        ),
    ]
